"""
Evidence PDF generator (ReportLab — already listed in the project's
root requirements.txt).

Structure follows the brief's spec: incident info, AI analysis,
evidence images, recommendations, and — mandatorily — a disclaimer
that this is AI-assisted screening, not a certified engineering
inspection.
"""

import io
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage,
)

from . import models

DISCLAIMER_TEXT = (
    "This document was generated by RailGuard, an AI-assisted visual screening "
    "system. It reports a computer-vision model's estimate of a possible track "
    "defect from a submitted photograph, and is <b>NOT</b> a certified railway "
    "engineering inspection, and does <b>NOT</b> constitute an official "
    "determination that any section of track is safe or unsafe. All AI-estimated "
    "severities in this report require confirmation by a qualified engineer or "
    "authorized railway personnel before any operational decision is made. "
    "Submission of this report to the platform does not, by itself, mean any "
    "railway authority has been notified — see the notification status below."
)


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(name="H1", parent=ss["Heading1"], fontSize=16, spaceAfter=6))
    ss.add(ParagraphStyle(name="H2", parent=ss["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4))
    ss.add(ParagraphStyle(name="Body", parent=ss["BodyText"], fontSize=9.5, leading=13))
    ss.add(ParagraphStyle(name="Small", parent=ss["BodyText"], fontSize=8, textColor=colors.grey))
    return ss


def build_report_pdf(
    report: models.Report,
    original_path: Optional[Path],
    annotated_path: Optional[Path],
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
    )
    ss = _styles()
    story = []

    sev = report.severity
    loc = report.location

    story.append(Paragraph("RailGuard — Track Defect Evidence Report", ss["H1"]))
    story.append(Paragraph(
        f"Report ID: <b>{report.id}</b> &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        ss["Small"],
    ))
    story.append(Spacer(1, 8))

    # ── Incident information ───────────────────────────────────
    story.append(Paragraph("Incident Information", ss["H2"]))
    incident_rows = [
        ["Report status", report.status],
        ["Submission method", report.source],
        ["Submitted at", report.created_at.strftime("%Y-%m-%d %H:%M UTC") if report.created_at else "—"],
        ["Original filename", report.original_filename or "—"],
    ]
    if loc:
        gps = f"{loc.lat:.5f}, {loc.lng:.5f} (±{loc.accuracy_m:.0f}m)" if loc.lat is not None and loc.lng is not None else "Not provided"
        incident_rows.append(["GPS coordinates", gps])
        incident_rows.append(["Nearest station", loc.nearest_station or "Not yet resolved"])
    else:
        incident_rows.append(["GPS coordinates", "Not provided"])
    story.append(_table(incident_rows))

    # ── AI analysis ─────────────────────────────────────────────
    story.append(Paragraph("AI Analysis (Computer Vision)", ss["H2"]))
    if sev:
        ai_rows = [
            ["AI-estimated severity", sev.ai_severity],
            ["Detections found", str(sev.ai_detection_count)],
            ["Max confidence", f"{sev.ai_max_confidence:.1%}"],
            ["Model", Path(sev.ai_model_path).name if sev.ai_model_path else "—"],
            ["Confidence threshold used", f"{(sev.ai_conf_threshold or 0):.0%}"],
        ]
        story.append(_table(ai_rows))
        if sev.ai_risk_summary:
            story.append(Spacer(1, 4))
            story.append(Paragraph(f"<b>Risk summary:</b> {sev.ai_risk_summary}", ss["Body"]))
    else:
        story.append(Paragraph("No detection data available.", ss["Body"]))

    # ── Engineering assessment (only if a human has verified) ───
    story.append(Paragraph("Engineering Assessment", ss["H2"]))
    if sev and sev.engineering_severity:
        eng_rows = [
            ["Engineering severity", sev.engineering_severity],
            ["Verified by", sev.verified_by or "—"],
            ["Verified at", sev.verified_at.strftime("%Y-%m-%d %H:%M UTC") if sev.verified_at else "—"],
        ]
        story.append(_table(eng_rows))
        if sev.engineering_notes:
            story.append(Spacer(1, 4))
            story.append(Paragraph(f"<b>Notes:</b> {sev.engineering_notes}", ss["Body"]))
    else:
        story.append(Paragraph(
            "Not yet reviewed by a qualified engineer or authorized railway "
            "personnel. This section will be populated once a human verification "
            "is recorded.", ss["Body"],
        ))

    # ── Evidence images ──────────────────────────────────────────
    story.append(Paragraph("Evidence", ss["H2"]))
    img_row = []
    for label, p in (("Original", original_path), ("Annotated", annotated_path)):
        if p and p.exists():
            try:
                img_row.append(RLImage(str(p), width=80 * mm, height=60 * mm, kind="proportional"))
            except Exception:
                pass
    if img_row:
        t = Table([img_row], colWidths=[85 * mm] * len(img_row))
        t.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
        story.append(t)
    else:
        story.append(Paragraph("Evidence images unavailable.", ss["Body"]))

    # ── Recommendations ──────────────────────────────────────────
    story.append(Paragraph("Recommended Actions (AI-suggested)", ss["H2"]))
    if sev and sev.ai_actions:
        for a in sev.ai_actions:
            story.append(Paragraph(f"• {a}", ss["Body"]))
    else:
        story.append(Paragraph("No specific actions generated.", ss["Body"]))

    # ── Disclaimer ────────────────────────────────────────────────
    story.append(Spacer(1, 14))
    story.append(Paragraph("Disclaimer", ss["H2"]))
    story.append(Paragraph(DISCLAIMER_TEXT, ss["Body"]))

    doc.build(story)
    return buf.getvalue()


def _table(rows):
    t = Table(rows, colWidths=[55 * mm, 110 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#4b5766")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
    ]))
    return t
